###0.importing

In [47]:
import numpy as np

###1. Creating numpy array


a) from list( vecctor operations work on array, but not on list)

In [48]:
list1=[2,4,6,8]
arr1=np.array(list1)

In [49]:
arr1

array([2, 4, 6, 8])

In [50]:
arr1+1

array([3, 5, 7, 9])

b) from 2D list

In [51]:
list2=[[1,2,3,4],[2,4,6,8]]
arr2=np.array(list2)

In [52]:
arr2

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

c)converting arrray type

In [53]:
arr2=np.array(list2,dtype='float')

In [54]:
arr2

array([[1., 2., 3., 4.],
       [2., 4., 6., 8.]])

d)converting array to list

In [55]:
arra=np.array([1,2,3,4,5,6,7],dtype='int')
lis=arra.tolist()

In [56]:
lis

[1, 2, 3, 4, 5, 6, 7]

###2.Array Dimensions

In [57]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [58]:
arr.shape

(2, 4)

In [59]:
arr.size

8

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr.ndim

2

###3.Reversing rows and columns

In [62]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

a)reversing rows

In [63]:
arr[::-1,]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

b)reversing rows and columns

In [64]:
arr[::-1,::-1]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

###4.Specific Element extraction

In [65]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr[:,1]

array([2, 6])

In [67]:
arr[0,:]

array([1, 2, 3, 4])

In [68]:
arr[:,-1]

array([4, 8])

In [69]:
arr[:,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

###5.Basic Statistics

In [70]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
arr.min()

1

In [72]:
arr.max()

8

In [73]:
arr.sum()

36

In [74]:
arr.mean()

4.5

In [75]:
np.median(arr)

4.5

In [76]:
np.average(arr)

4.5

In [77]:
np.var(arr)

5.25

In [78]:
np.average(arr)

4.5

In [79]:
np.average(arr[0])

2.5

###6.Reshaping and Flattening

In [80]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
arr.shape

(2, 4)

In [82]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [83]:
arr.reshape(1,1,8)

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [84]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

###7.Creating Random Arrays and Sequences

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(2,10,3)

array([2, 5, 8])

In [89]:
np.arange(10,1)

array([], dtype=int64)

In [90]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [91]:
np.linspace(start=1, stop = 10, num = 3)

array([ 1. ,  5.5, 10. ])

In [92]:
np.linspace(start=1, stop = 10, num = 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [93]:
np.linspace(start=1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [94]:
np.zeros([10, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [95]:
np.zeros([2, 3, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

###8.Unique Items and Count